{% set name = "pyjwkest" %}
{% set version = "1.4.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbfd6ab26c30ae710215ebabf590441d551bf0a8a6c95b33c3d0738062a56562

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - future
    - pycryptodomex
    - python >={{ python_min }}
    - requests
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - jwkest

about:
  home: https://github.com/IdentityPython/pyjwkest
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python implementation of JWT, JWE, JWS and JWK

extra:
  recipe-maintainers:
    - mariusvniekerk
