{% set name = "pyjwkest" %}
{% set version = "1.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5560fd5ba08655f29ff6ad1df1e15dc05abc9d976fcbcec8d2b5167f49b70222

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - future
    - pycryptodomex
    - python >={{ python_min }}
    - requests
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - jwkest

about:
  home: https://github.com/IdentityPython/pyjwkest
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python implementation of JWT, JWE, JWS and JWK

extra:
  recipe-maintainers:
    - mariusvniekerk
